// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepositoryLayer.ModelContext;

namespace RepositoryLayer.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20200408084355_voterstables")]
    partial class voterstables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CommonLayer.Model.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AdmContactNumber");

                    b.Property<string>("AdmEmail")
                        .IsRequired();

                    b.Property<string>("AdmFirstName")
                        .IsRequired();

                    b.Property<string>("AdmLastName")
                        .IsRequired();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.HasKey("AdminId");

                    b.HasIndex("AdmEmail")
                        .IsUnique();

                    b.ToTable("admins");
                });

            modelBuilder.Entity("CommonLayer.Model.AdminCandidate", b =>
                {
                    b.Property<int>("AdminCandidateId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId");

                    b.Property<int>("CandidateId");

                    b.HasKey("AdminCandidateId");

                    b.ToTable("adminCandidates");
                });

            modelBuilder.Entity("CommonLayer.Model.AdminConstituency", b =>
                {
                    b.Property<int>("AdminConstId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId");

                    b.Property<int>("ConstituencyId");

                    b.HasKey("AdminConstId");

                    b.ToTable("adminConstituencies");
                });

            modelBuilder.Entity("CommonLayer.Model.AdminParty", b =>
                {
                    b.Property<int>("AdminPartyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId");

                    b.Property<int>("PartyId");

                    b.HasKey("AdminPartyId");

                    b.ToTable("adminParties");
                });

            modelBuilder.Entity("CommonLayer.Model.AdminVoter", b =>
                {
                    b.Property<int>("AdminVoterId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId");

                    b.Property<int>("VoterId");

                    b.HasKey("AdminVoterId");

                    b.ToTable("adminVoters");
                });

            modelBuilder.Entity("CommonLayer.Model.Candidate", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId");

                    b.Property<string>("CandidateFirstName")
                        .IsRequired();

                    b.Property<string>("CandidateLastName")
                        .IsRequired();

                    b.Property<long>("CandidatePhoneNumber");

                    b.Property<int>("ConstituencyId");

                    b.Property<DateTime>("Created");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("PartyId");

                    b.Property<int>("Votes");

                    b.HasKey("CandidateId");

                    b.HasIndex("CandidatePhoneNumber")
                        .IsUnique();

                    b.ToTable("candidates");
                });

            modelBuilder.Entity("CommonLayer.Model.Constituency", b =>
                {
                    b.Property<int>("ConstituencyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId");

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("ConstituencyName")
                        .IsRequired();

                    b.Property<DateTime>("Created");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("State")
                        .IsRequired();

                    b.HasKey("ConstituencyId");

                    b.ToTable("constituencies");
                });

            modelBuilder.Entity("CommonLayer.Model.Party", b =>
                {
                    b.Property<int>("PartyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId");

                    b.Property<DateTime>("Created");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("PartyName")
                        .IsRequired();

                    b.HasKey("PartyId");

                    b.ToTable("parties");
                });

            modelBuilder.Entity("CommonLayer.Model.Voter", b =>
                {
                    b.Property<int>("VoterId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CandidateId");

                    b.Property<DateTime>("Created");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("Modified");

                    b.Property<long>("UniqueVoterId");

                    b.Property<long>("VoterContactNUmber");

                    b.Property<string>("VoterFirstName");

                    b.Property<string>("VoterLastName");

                    b.HasKey("VoterId");

                    b.ToTable("voters");
                });

            modelBuilder.Entity("CommonLayer.ResponseModel.AdminResponse", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AdminContactNumber");

                    b.Property<string>("AdminEmail");

                    b.Property<string>("AdminFirstName");

                    b.Property<string>("AdminLastName");

                    b.Property<int?>("CandidateId");

                    b.Property<int?>("ConstituencyId");

                    b.Property<int?>("PartyId");

                    b.HasKey("AdminId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("ConstituencyId");

                    b.HasIndex("PartyId");

                    b.ToTable("AdminResponse");
                });

            modelBuilder.Entity("CommonLayer.ResponseModel.AdminResponse", b =>
                {
                    b.HasOne("CommonLayer.Model.Candidate")
                        .WithMany("AdminResponses")
                        .HasForeignKey("CandidateId");

                    b.HasOne("CommonLayer.Model.Constituency")
                        .WithMany("AdminResponses")
                        .HasForeignKey("ConstituencyId");

                    b.HasOne("CommonLayer.Model.Party")
                        .WithMany("AdminResponses")
                        .HasForeignKey("PartyId");
                });
#pragma warning restore 612, 618
        }
    }
}
